### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by oliverwoodings** [QubitProducts/react-test-tree#30]
This is going to break a lot of stuff :sob:. At a first glance I believe we are going to need to find a method of retrieving the component of a DOM node (i.e. the reverse of `React.findDOMNode`).

**Comment by oliverwoodings** [comment]
After doing some digging we should still be ok. React adds '_reactInternalComponent' to all DOM nodes it renders so you can still access it's data. Also if you nest a React classes you will get the class itself as a ref, not it's DOM node, which is handy. This means that we need to split the TestNode class into two different types: classes and elements. Elements don't have their own child refs so are much simpler.

**Comment by aguestuser** [comment]
Any updates on this? Is a patch still actively being worked on? This issue was opened in July and it looks like the [react0.14 branch](https://github.com/QubitProducts/react-test-tree/blob/react0.14/package.json) was last committed to in July as well. Are there still plans to patch the library to work with v0.14? I ask because am in the middle of transitioning to v0.14 for a new project, LOVE this testing library, and would hate to abandon it due to compatibilty issues. Is there a move afoot to simply standardize around Facebook's `TestUtils` of which I should be aware?

**Comment by oliverwoodings** [comment]
Hi Augustin, I am working on it, it just takes time since 0.14 broke a lot
of stuff. I'm hoping to have an rc ready today.

**Comment by oliverwoodings** [comment]
Sorry, meant Austin!

**Comment by aguestuser** [comment]
Thanks Oliver. No worries at all! Breaking changes in someone else's library are always the worst! Look forward to seeing how you field them. In general: thanks for all the hard work and the great library! (And no worries about the the name either -- I actually quite like Agustin! :smiley_cat:)

**Comment by doctyper** [comment]
:+1: would love to keep this helper for our `0.14` migration.

**Comment by oliverwoodings** [comment]
Made good progress today - should have an RC tomorrow morning. There will be some breaking API changes, I'll be documenting them soon!

**Comment by aguestuser** [comment]
WOOHOO! :100:

**Comment by oliverwoodings** [comment]
This is currently the biggest blocker on releasing 0.14 support: https://github.com/QubitProducts/react-test-tree/issues/49

**Comment by oliverwoodings** [comment]
1.0.0-rc2 has been released

**Comment by oliverwoodings** [comment]
1.0.0-rc3 has been released

**Comment by oliverwoodings** [comment]
1.0.0-rc5 has been released, this will hopefully be the final rc before merging.

**Comment by oliverwoodings** [comment]
1.0.0 is now released!
