### ISSUE TITLE
Support simulating additional events

### ISSUE THREAD

**Issue by joeybaker** [QubitProducts/react-test-tree#33]
It would be great if additional events were supported in as a method on `node.simulate`. We're using https://www.npmjs.com/package/react-tap-event-plugin and haven't found a way to use test tree to test these actions.

**Comment by oliverwoodings** [comment]
Interesting idea, would you like a way to register additional simulation
methods with the global test tree instance?

**Comment by joeybaker** [comment]
I haven't dug into how test tree does this, but ideally, it would just grab everything off of `react/lib/EventPluginHub`. Failing that, yea, a way to register a new even with test tree would be great.

**Comment by oliverwoodings** [comment]
I'm actually a bit confused as to why it isn't already picking up the custom events, since it reads everything straight off TestUtils.Simulate whenever a tree is created. As long as you are injecting the tap event plugin before using the `testTree` function it should pick up those events.

I guess the most bullet proof solution here would be for me to copy React's own Simulate functionality where they rebuilt the Simulate object every time the EventPluginHub has a new registration (https://github.com/facebook/react/blob/2ea0bd77b47f2b042198854f11d6d584a0ded554/src/test/ReactTestUtils.js#L485)

**Comment by aguestuser** [comment]
+1 to this! I'm using the fantastic [react-tappable component](https://github.com/JedWatson/react-tappable), which provides an `onPress` event handler.

[Using it in this component](https://github.com/the-learning-collective/whereat-web/blob/ffa5a2e5378a40e4732885f65476187373c1534c/src/components/GoButton.jsx#L15-L21) works as expected when running, but I am unable to place the behavior under test.

[This spec](https://github.com/the-learning-collective/whereat-web/blob/ffa5a2e5378a40e4732885f65476187373c1534c/test/components/GoButton.spec.js#L76-L88):

```javascript
  xdescribe('pressing go button', () => {

    it('calls shareActions#poll', (done) => {
      const [app, {togglePoll}] = setup(RED);
      const gb = testTree(<GoButton />, {context: {app: app}});

      press(gb).should.be.fulfilled
        .then(() => togglePoll.should.have.been.calledOnce)
        .should.notify(done);

      // TODO: how to simulate a long press?
    });
  });
```

With [this handrolled simulation function](https://github.com/the-learning-collective/whereat-web/blob/ffa5a2e5378a40e4732885f65476187373c1534c/test/components/GoButton.spec.js#L42-L47):

```javascript
  const press = (node) => (
    Promise.resolve()
      .then(() => node.simulate.touchStart)
      .then(() => wait(1))
      .then(() => node.simulate.touchEnd)
  );
```

Was my shoddy (and failed) attempt to hand-roll a workaround.

Does anyone else trying to do this have suggested work-arounds and/or is there energy from maintainers to implement this? Hard to figure out how you'd do it since `press` isn't an event supported by the underlying React TestUtils library.

That said, it's an EXTREMELY common event in mobile apps (occurs natively in Android and IOS), so if trying to use React for mobile web work, it's somewhat crippling (from a testing perspective anyway) to not be able to put that behavior under test.

/a/

**Comment by aguestuser** [comment]
Hi all. FWIW: I was able to resolve my particular issue fairly easily. Problem reduced to a failure to invoke the simulation methods I wanted to call. Rewriting the above as follows worked just fine to simulate a `longPress`:

```javascript
  const press = (node) => (
    Promise.resolve()
      .then(() => node.simulate.mouseDown())
      .then(() => wait(1))
      .then(() => node.simulate.mouseUp())
  );
```
Although the invokation gotcha is pretty straightforward, I thought it might be easy to overlook for someone who'd only read the docs and wasn't familiar with React TestUtils simulation methods, so I [sumbitted a PR](https://github.com/QubitProducts/react-test-tree/pull/35) with a brief explanatory example. 

@oliverwoodings: hope that's helpful and not annoying! SUPER appreciative of the great work y'all are doing on marty and testing in the React space! Great tools and LOVE using them! :smile_cat:

**Comment by oliverwoodings** [comment]
@joeybaker would you mind showing me a scenario where you can't get the tap event plugin to work? I just added a test case to make sure simulate library addons are correctly applied to nodes and it is already passing without me changing anything: b0f8c5bbfcf8e9736c31d79077d73ed259890426 https://travis-ci.org/QubitProducts/react-test-tree/builds/74389501

**Comment by oliverwoodings** [comment]
Closing this for now, I've added extra test cases in #38 to ensure this should all work. Please let me know if there is still an issue.

**Comment by joeybaker** [comment]
@oliverwoodings Thanks for taking the time! I'll double check that I'm wrong :)

**Comment by oliverwoodings** [comment]
Just make sure you are injecting the events before you create the test tree
