### ISSUE TITLE
Ignoring Higher Order Components

### ISSUE THREAD

**Issue by jhollingworth** [QubitProducts/react-test-tree#34]
Its become [common in the react world to use function composition to add additional to components](https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750), known as [higher order components](https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775). Unfortunately they mess with a components refs which makes testing with test-tree a pain.

I'd like a way to tell test-tree that a component is a HOC which would mean test tree essentially skips the component. Things like stubbing would be automatically handled for you as well

```js
const something = InnerComponent => class HigherOrderComponent extends React.Component {
  render () {
    return <InnerComponent ref='innerComponent' __highOrderComponent={true} {...this.props}/>
  }
}

@something
class Foo extends React.Component {
   render () {
     return <div ref='bar'>Woo</div>
   }
}

const foo = tree(<Foo />)

console.log(foo.bar.innerText)
```

**Comment by oliverwoodings** [comment]
So one issue I can think of with this approach is if you are using HOC from other libraries. It is unlikely that they would have the `__highOrderComponent={true}`. What would you want to happen if you are using a HOC that you can't directly modify?

**Comment by jhollingworth** [comment]
You could optionally have it as a static property of the class

```js
import {SomeComponent} from 'something'

SomeComponent.__higherOrderComponent = 'innerComponent'
```

**Comment by oliverwoodings** [comment]
What is `SomeComponent` in this case? The HOC or the inner component?

**Comment by jhollingworth** [comment]
The HOC

**Comment by oliverwoodings** [comment]
So I think I would prefer to have only one solution to this problem, and I quite like the idea of assigning a static property to the HOC since it feels very declarative and uniform.

Only final thing to discuss is the naming. To me this doesn't make much sense when reading it:

```js
SomeComponent.__higherOrderComponent = "innerComponent"
```

It makes it sound like `SomeComponent` is the inner component, but then you are setting a static property called `higherOrderComponent`, but then that is set to `innerComponent`, and by this point i've lost the will to live.

![](http://www.reactiongifs.com/wp-content/uploads/2013/05/nonsense.gif)


How about:

```js
MyHOC.innerComponentRef = "innerComponent"
```

?

**Comment by jhollingworth** [comment]
sure
