### ISSUE TITLE
Document is not defined.

### ISSUE THREAD

**Issue by tnrich** [QubitProducts/react-test-tree#42]
Hitting this error while trying to use your library:
 ReferenceError: document is not defined
      at Object.testTree [as default] (node_modules/react-test-tree/lib/testTree.js:14:19)
      at Context.<anonymous> (test/InfiniteScroller.js:88:19)

I didn't see jsdom being referenced anywhere. Is it necessary to have the DOM for this module to work?

**Comment by oliverwoodings** [comment]
Hi, yes it is necessary to have a DOM. If you are testing in Node then you will need to run something like jsdom. This is due to React itself, not test-tree. Even React's own test utilities require you to have a DOM in order to render in tests: https://facebook.github.io/react/docs/test-utils.html

I will add a note to the readme
