### ISSUE TITLE
ref="value" doesn't return the element

### ISSUE THREAD

**Issue by jhollingworth** [QubitProducts/react-test-tree#9]
If you have an element whose ref is `value` then it returns undefined

**Comment by oliverwoodings** [comment]
That's really weird... I'll look into it

**Comment by oliverwoodings** [comment]
Don't know why I thought that was weird, it makes sense since 'value' is a property on TestNode: https://github.com/QubitProducts/react-test-tree/blob/master/lib/testNode.js#L35

Can probably make this less of a 'black hole' by adding `value` to the list of [protected keys](https://github.com/QubitProducts/react-test-tree/blob/master/lib/testNode.js#L49)
